### ISSUE TITLE
Set time in datetime field

### ISSUE THREAD

**Issue by ballinger** [enm10k/nocodb-mobile#23]
Slowly starting to use it :) something is off setting the time for a datetime column. Seems to work after second attempt.

**Comment by enm10k** [comment]
Thanks for your feedback.

> something is off setting the time for a datetime column. Seems to work after second attempt.

I was able to reproduce the problem
When registering a new record, the time selection dialog is being skipped.
I will check.

**Comment by enm10k** [comment]
Thanks for yourr feedback.
The problem is fixed in #25.
