### ISSUE TITLE
[ feature req ] Refresh on pull down

### ISSUE THREAD

**Issue by ballinger** [enm10k/nocodb-mobile#27]
Refresh content with swipe down gesture. Previous fixes working, thanks!

**Comment by enm10k** [comment]
Implemented in #28.

**Comment by enm10k** [comment]
Let me provide some background.
Since swipe down gesture is difficult to use when many rows are loaded, I added a button to refresh content in the bottom app bar.

**Comment by ballinger** [comment]
Cool, works for me. Thanx!
