### ISSUE TITLE
Can´t connect to the database

### ISSUE THREAD

**Issue by JaimePayan** [enm10k/nocodb-mobile#9]
Hi, noob here, I.m trying to connect to anocodb databe but I cannot find the API endpoint that the app ask for login, where I can find this info?

Thank you in advance
Jaime

**Comment by enm10k** [comment]
Please enter the domain of the NocoDB you are deploying in the API Endpoint field.

https://github.com/enm10k/nocodb-mobile/blob/e398914e296bbe94a9c4c9f54395be93a3ba4e7f/lib/nocodb_sdk/client.dart#L188-L194
